     jobs:
       deploy:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v2
           - name: Build and Deploy
             run: |
               echo "window.__APP_CONFIG__ = { API_KEY: '${{ secrets.API_KEY }}' };" > ./public/config.js
     
