name: Process Comments Script

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Подставить секрет в JS
        env:
          COMMENTS_API_KEY: ${{ secrets.COMMENTS_API_KEY }}
        run: |
          sed -i 's/GITHUB_SECRET_PLACEHOLDER/$COMMENTS_API_KEY/g' assets/js/comments.js
      
      - name: Деплой
        uses: some-deploy-action@v3
