name: Update Feedback

on:
  push:
    branches:
      - main

jobs:
  update-feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update feedback file
        run: node updateFeedback.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add feedback.json
          git commit -m 'Update feedback'
          git push
